#include "gameSounds.h"

// basic mapping of sound type to a file path
const char* toFilePath(SoundType sound) {
    switch (sound) {
		case SoundType::ROACH_NOISE:
			return "../resource/sounds/ROACH_NOISE.wav";
		case SoundType::SPITTER_NOISE:
			return "../resource/sounds/SPITTER_NOISE.wav";
		case SoundType::SPEWER_NOISE:
			return "../resource/sounds/SPEWER_NOISE.wav";
		case SoundType::SPAWNER_NOISE:
			return "../resource/sounds/SPAWNER_NOISE.wav";
		case SoundType::EXPLODER_NOISE:
			return "../resource/sounds/EXPLODER_NOISE.wav";
		case SoundType::ALPHASPITTER_NOISE:
			return "../resource/sounds/ALPHASPITTER_NOISE.wav";
		case SoundType::CHARGER_NOISE:
			return "../resource/sounds/CHARGER_NOISE.wav";
		case SoundType::ALPHACHARGER_NOISE:
			return "../resource/sounds/ALPHACHARGER_NOISE.wav";
		case SoundType::ALPHASPEWER_NOISE:
			return "../resource/sounds/ALPHASPEWER_NOISE.wav";
		case SoundType::BURROWER_NOISE:
			return "../resource/sounds/BURROWER_NOISE.wav";
		case SoundType::BURROWER_DIG:
			return "../resource/sounds/BURROWER_DIG.wav";
		case SoundType::SPIT_HIGH:
			return "../resource/sounds/SPIT_HIGH.wav";
		case SoundType::SPIT_LOW:
			return "../resource/sounds/SPIT_LOW.wav";
		case SoundType::SPIT_MEDIUM:
			return "../resource/sounds/SPIT_MEDIUM.wav";
		case SoundType::BUG_DEATH1:
			return "../resource/sounds/BUG_DEATH.mp3";
		case SoundType::BUG_DEATH2:
			return "../resource/sounds/BUG_DEATH1.mp3";
		case SoundType::PLAYER_DAMAGE1:
			return "../resource/sounds/PLAYER_DAMAGE1.wav";
		case SoundType::PLAYER_DAMAGE2:
			return "../resource/sounds/PLAYER_DAMAGE2.wav";
		case SoundType::PLAYER_DAMAGE3:
			return "../resource/sounds/PLAYER_DAMAGE3.wav";
		case SoundType::PLAYER_DAMAGE4:
			return "../resource/sounds/PLAYER_DAMAGE4.wav";
		case SoundType::PLAYER_DAMAGE5:
			return "../resource/sounds/PLAYER_DAMAGE5.wav";
		case SoundType::PLAYER_DAMAGE6:
			return "../resource/sounds/PLAYER_DAMAGE6.wav";
		case SoundType::PLAYER_KILLS1:
			return "../resource/sounds/PLAYER_KILLS1.wav";
		case SoundType::PLAYER_KILLS2:
			return "../resource/sounds/PLAYER_KILLS2.wav";
		case SoundType::PLAYER_KILLS3:
			return "../resource/sounds/PLAYER_KILLS3.wav";
		case SoundType::PLAYER_KILLS4:
			return "../resource/sounds/PLAYER_KILLS4.wav";
		case SoundType::PLAYER_KILLS5:
			return "../resource/sounds/PLAYER_KILLS5.wav";
		case SoundType::PLAYER_KILLS6:
			return "../resource/sounds/PLAYER_KILLS6.mp3";
		case SoundType::PLAYER_KILLS7:
			return "../resource/sounds/PLAYER_KILLS7.wav";
		case SoundType::PLAYER_KILLS8:
			return "../resource/sounds/PLAYER_KILLS8.wav";
		case SoundType::DOOR_OPEN:
			return "../resource/sounds/DOOR_OPEN.wav";
		case SoundType::DOOR_CLOSE:
			return "../resource/sounds/DOOR_CLOSE.wav";
		case SoundType::PLAYER_SAD1:
			return "../resource/sounds/PLAYER_SAD1.wav";
		case SoundType::PLAYER_SAD2:
			return "../resource/sounds/PLAYER_SAD2.wav";
		case SoundType::PLAYER_SAD3:
			return "../resource/sounds/PLAYER_SAD3.wav";
		case SoundType::PLAYER_SAD4:
			return "../resource/sounds/PLAYER_SAD4.wav";
		case SoundType::PLAYER_SAD5:
			return "../resource/sounds/PLAYER_SAD5.wav";
		case SoundType::PLAYER_SAD6:
			return "../resource/sounds/PLAYER_SAD6.wav";
		case SoundType::PLAYER_SHOOT:
			return "../resource/sounds/PLAYER_SHOOT.wav";
		case SoundType::EXPLOSION:
			return "../resource/sounds/EXPLOSION.wav";
		case SoundType::PICKUP:
			return "../resource/sounds/PICKUP.wav";
		case SoundType::ROLL:
			return "../resource/sounds/ROLL.wav";
		case SoundType::ALIENQUEEN1:
			return "../resource/sounds/ALIENQUEEN1.mp3";
		case SoundType::ALIENQUEEN2:
			return "../resource/sounds/ALIENQUEEN2.mp3";
        default:
            return "";
    }
}